config/routes.rb
Rails.application.routes.draw do
  get "locations/index"
  get "locations/export"
  get "locations/lokacije"
  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'locations#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  resources :assets

  resources :technical_goods_assortments

  resources :brands

  resources :products

  resources :primary_assortments

  resources :locations_assortments

  resources :sales_specialists

  resources :places

  resources :regions

  resources :locations
   resources :locations do 
    collection do 
      get 'locations/export', :to => 'locations#export'
    end
  end
  get "companies/index"
  get "companies/show"
  get "companies/new"
  get "companies/edit"
   root 'locations#index'
    authenticate :user do
    resources :locations, only: [:new, :create, :edit, :update, :destroy]
    resources :regions, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/ap_brand.rb
class ApBrand < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/ap_product.rb
class ApProduct < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :location , :class_name => "Location"
  attr_accessible :avatar_file_name
  attr_accessible :position, :class_type, :alt, :attachment_width , :attachment_height ,:avatar , :class_type , :typeable_id
  alias_attribute :location_id, :typeable_id
  has_attached_file :avatar, styles: { mini: '48x48#',
                                      small: '150x120>',
                                      home: '185x185#',
                                      product: '240x240>',
  	large: '570x380>' },
    :url  => "/assets/locations/:typeable_id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/locations/:typeable_id/:style/:basename.:extension"
     Paperclip.interpolates :typeable_id do |attachment, style|
    "#{attachment.instance.typeable_id}"
  end
  Paperclip.options[:content_type_mappings] = { jpeg: 'image/jpeg', jpg: 'image/jpeg' }

	
end

app/models/brand.rb
class ApBrand < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_xlsx
	include ActiveModel::ForbiddenAttributesProtection
	include ActiveModel::MassAssignmentSecurity
=begin	 has_attached_file :avatar, styles: { mini: '48x48#',
                                         small: '150x120>',
                                         home: '185x185#',
                                         product: '240x240>',
  									     large: '570x380>' },
    :url  => "/assets/locations/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/locations/:id/:style/:basename.:extension"
	validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
=end
  attr_accessible :address, :latitude, :longitude, :name ,:region_id , :place_id , :customer_character , :contact, :sales_specialist_id , :tel_fax_email , :object_type , :customer_classification , :class_type 
  attr_accessible :asset_params
  belongs_to :sales_specialist
  belongs_to :region
  belongs_to :place
  has_many :locations_assortments , :dependent => :destroy
  has_many :technical_goods_assortments, :dependent => :destroy
  has_many :assets , :dependent => :destroy ,  :foreign_key => 'typeable_id'
  has_many :products , :through => :technical_goods_assortments
  accepts_nested_attributes_for :assets, allow_destroy: true
  accepts_nested_attributes_for :locations_assortments, allow_destroy: true
  accepts_nested_attributes_for :technical_goods_assortments, allow_destroy: true
  attr_accessible :locations_assortments_attributes
  attr_accessible :technical_goods_assortments_attributes
  validates :address, :name ,:region_id , :place_id , :customer_character , :contact, :sales_specialist_id , :tel_fax_email , :object_type , :customer_classification , presence: true 
  geocoded_by :address
	after_validation :geocode , if: ->(obj){ obj.address.present? and obj.address_changed? }
  
  def gmaps4rails_address
      address
  end
 
end

app/models/locations_assortment.rb
class LocationsAssortment < ActiveRecord::Base
	belongs_to :location
	belongs_to :primary_assortment
	attr_accessible :assortment_id , :location_id
end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :locations
	belongs_to :region
	
end

app/models/product.rb
class ApProduct < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :locations
	has_many :places
	
end

app/models/sales_specialist.rb
class SalesSpecialist < ActiveRecord::Base
	has_many :locations
	attr_accessible :name, :phone
	validates :name, :phone, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #before_action :authenticate_user!
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :location
  attr_accessor :username
  attr_accessible :email
  attr_accessible :password
  attr_accessible :password_confirmation
  attr_accessible :first_name
  attr_accessible :last_name,
  #attr_accessible :encrypted_password ,:reset_password_token,:reset_password_sent_at , :remember_created_at ,
  #:current_sign_in_at,
  #:last_sign_in_at,
  #:current_sign_in_ip ,
  #:last_sign_in_ip ,
  :created_at ,
  :updated_at 
end

app/controllers/locations_assortments_controller.rb
class LocationsAssortmentsController < ApplicationController
  before_action :set_locations_assortment, only: [:show, :edit, :update, :destroy]

  # GET /locations_assortments
  # GET /locations_assortments.json
  def index
    @locations_assortments = LocationsAssortment.all
  end

  # GET /locations_assortments/1
  # GET /locations_assortments/1.json
  def show
  end

  # GET /locations_assortments/new
  def new
    @locations_assortment = LocationsAssortment.new
  end

  # GET /locations_assortments/1/edit
  def edit
  end

  # POST /locations_assortments
  # POST /locations_assortments.json
  def create
    @locations_assortment = LocationsAssortment.new(locations_assortment_params)

    respond_to do |format|
      if @locations_assortment.save
        format.html { redirect_to @locations_assortment, notice: 'Locations assortment was successfully created.' }
        format.json { render :show, status: :created, location: @locations_assortment }
      else
        format.html { render :new }
        format.json { render json: @locations_assortment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations_assortments/1
  # PATCH/PUT /locations_assortments/1.json
  def update
    respond_to do |format|
      if @locations_assortment.update(locations_assortment_params)
        format.html { redirect_to @locations_assortment, notice: 'Locations assortment was successfully updated.' }
        format.json { render :show, status: :ok, location: @locations_assortment }
      else
        format.html { render :edit }
        format.json { render json: @locations_assortment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations_assortments/1
  # DELETE /locations_assortments/1.json
  def destroy
    @locations_assortment.destroy
    respond_to do |format|
      format.html { redirect_to locations_assortments_url, notice: 'Locations assortment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locations_assortment
      @locations_assortment = LocationsAssortment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locations_assortment_params
      params.require(:locations_assortment).permit(:assortment_id, :location_id)
    end
end

app/helpers/ap_brands_helper.rb
module ApBrandsHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/brands_helper.rb
module ApBrandsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_assortments_helper.rb
module LocationsAssortmentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper

		def slick_slider_image(asset)
		link_to(image_tag(asset.avatar.url(:home) , size:'165x165'))
	end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/products_helper.rb
module ApProductsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/locations_assortments/_form.html.erb
<%= form_for(@locations_assortment) do |f| %>
  <% if @locations_assortment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locations_assortment.errors.count, "error") %> prohibited this locations_assortment from being saved:</h2>

      <ul>
      <% @locations_assortment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asortiman %><br>
    <%= f.collection_select :assortment_id, PrimaryAssortment.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :lokacija %><br>
    <%= f.collection_select :location_id, Location.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Spasi" %>
  </div>
<% end %>

app/views/locations_assortments/edit.html.erb
<h1>Uredi lokacijski asortiman</h1>

<%= render 'form' %>

<%= link_to 'Show', @locations_assortment %> |
<%= link_to 'Back', locations_assortments_path %>

app/views/locations_assortments/index.html.erb
<h1>Listing lokacijskih asortimana</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Asortiman</th>
      <th>Lokacija</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations_assortments.each do |locations_assortment| %>
      <tr>
        <td><%= PrimaryAssortment.find(locations_assortment.assortment_id).name %></td>
        <td><%= Location.find(locations_assortment.location_id).name %></td>
        <td><%= link_to 'Show', locations_assortment %></td>
        <td><%= link_to 'Edit', edit_locations_assortment_path(locations_assortment) %></td>
        <td><%= link_to 'Destroy', locations_assortment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novi lokacijski asortiman', new_locations_assortment_path %>
<br>
<%= link_to 'Back', locations_path(@location, url_options), :data => {:no_turbolink =>true} %>

app/views/locations_assortments/new.html.erb
<h1>Novi lokacijski asortiman</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_assortments_path %>

app/views/locations_assortments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asortiman:</strong>
  <%= @locations_assortment.assortment_id %>
</p>

<p>
  <strong>Lokacija:</strong>
  <%= @locations_assortment.location_id %>
</p>

<%= link_to 'Edit', edit_locations_assortment_path(@locations_assortment) %> |
<%= link_to 'Back', locations_assortments_path %>