config/routes.rb
Rails.application.routes.draw do
  get "locations/index"
  get "locations/export"
  get "locations/lokacije"
  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'locations#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  resources :assets

  resources :technical_goods_assortments

  resources :brands

  resources :products

  resources :primary_assortments

  resources :locations_assortments

  resources :sales_specialists

  resources :places

  resources :regions

  resources :locations
   resources :locations do 
    collection do 
      get 'locations/export', :to => 'locations#export'
    end
  end
  get "companies/index"
  get "companies/show"
  get "companies/new"
  get "companies/edit"
   root 'locations#index'
    authenticate :user do
    resources :locations, only: [:new, :create, :edit, :update, :destroy]
    resources :regions, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/technical_goods_assortment.rb
class TechnicalGoodsAssortment < ActiveRecord::Base
	belongs_to :location
	has_many :products
	has_many :brands

	attr_accessible :ap1_id, :ap2_id, :ap3_id, :ap4_id, :ap5_id, :ap6_id, :ap7_id, :ap8_id, :b1_id, :b2_id, :b3_id, :b4_id, :b5_id, :b6_id , :location_id
	
	
end

app/controllers/technical_goods_assortments_controller.rb
class TechnicalGoodsAssortmentsController < ApplicationController
  before_action :set_technical_goods_assortment, only: [:show, :edit, :update, :destroy]

  # GET /technical_goods_assortments
  # GET /technical_goods_assortments.json
  def index
    @technical_goods_assortments = TechnicalGoodsAssortment.all
  end

  # GET /technical_goods_assortments/1
  # GET /technical_goods_assortments/1.json
  def show
  end

  # GET /technical_goods_assortments/new
  def new
    @technical_goods_assortment = TechnicalGoodsAssortment.new
  end

  # GET /technical_goods_assortments/1/edit
  def edit
  end

  # POST /technical_goods_assortments
  # POST /technical_goods_assortments.json
  def create
    @technical_goods_assortment = TechnicalGoodsAssortment.new(technical_goods_assortment_params)

    respond_to do |format|
      if @technical_goods_assortment.save
        format.html { redirect_to @technical_goods_assortment, notice: 'Technical goods assortment was successfully created.' }
        format.json { render :show, status: :created, location: @technical_goods_assortment }
      else
        format.html { render :new }
        format.json { render json: @technical_goods_assortment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technical_goods_assortments/1
  # PATCH/PUT /technical_goods_assortments/1.json
  def update
    respond_to do |format|
      if @technical_goods_assortment.update(technical_goods_assortment_params)
        format.html { redirect_to @technical_goods_assortment, notice: 'Technical goods assortment was successfully updated.' }
        format.json { render :show, status: :ok, location: @technical_goods_assortment }
      else
        format.html { render :edit }
        format.json { render json: @technical_goods_assortment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technical_goods_assortments/1
  # DELETE /technical_goods_assortments/1.json
  def destroy
    @technical_goods_assortment.destroy
    respond_to do |format|
      format.html { redirect_to technical_goods_assortments_url, notice: 'Technical goods assortment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technical_goods_assortment
      @technical_goods_assortment = TechnicalGoodsAssortment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technical_goods_assortment_params
      params.require(:technical_goods_assortment).permit(:ap1_id, :ap2_id, :ap3_id, :ap4_id, :ap5_id, :ap6_id, :ap7_id, :ap8_id, :b1_id, :b2_id, :b3_id, :b4_id, :b5_id, :b6_id , :location_id)
    end
end

app/helpers/technical_goods_assortments_helper.rb
module TechnicalGoodsAssortmentsHelper
end

app/views/technical_goods_assortments/_form.html.erb
<%= form_for(@technical_goods_assortment) do |f| %>
  <% if @technical_goods_assortment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technical_goods_assortment.errors.count, "error") %> prohibited this technical_goods_assortment from being saved:</h2>

      <ul>
      <% @technical_goods_assortment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ap1_id %><br>
    <%= f.collection_select :ap1_id , ApProduct.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :ap2_id %><br>
     <%= f.collection_select :ap2_id , ApProduct.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :ap3_id %><br>
     <%= f.collection_select :ap3_id , ApProduct.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :ap4_id %><br>
     <%= f.collection_select :ap4_id , ApProduct.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :ap5_id %><br>
     <%= f.collection_select :ap5_id , ApProduct.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :ap6_id %><br>
     <%= f.collection_select :ap6_id , ApProduct.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :ap7_id %><br>
     <%= f.collection_select :ap7_id , ApProduct.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :ap8_id %><br>
     <%= f.collection_select :ap8_id , ApProduct.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div style="  margin-left: 300px;
  margin-top: -384px;">
  <div class="field">
    <%= f.label :b1_id %><br>
     <%= f.collection_select :b1_id , ApBrand.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :b2_id %><br>
   <%= f.collection_select :b2_id , ApBrand.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :b3_id %><br>
    <%= f.collection_select :b3_id , ApBrand.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :b4_id %><br>
    <%= f.collection_select :b4_id , ApBrand.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :b5_id %><br>
    <%= f.collection_select :b5_id , ApBrand.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :b6_id %><br>
   <%= f.collection_select :b6_id , ApBrand.all, :id, :name , {:class => 'select_class'}%>
  </div>
  <div class="field">
    <%= f.label :lokacija %><br>
    <%= f.collection_select :location_id , Location.all, :id, :name , {:class => 'select_class'}%>
  </div>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Spasi" %>
  </div>
<% end %>

app/views/technical_goods_assortments/edit.html.erb
<h1>Uredi asortiman tehnickih roba</h1>

<%= render 'form' %>

<%= link_to 'Show', @technical_goods_assortment %> |
<%= link_to 'Back', technical_goods_assortments_path %>

app/views/technical_goods_assortments/index.html.erb
<h1 style="  margin-left: -280px;">Listing asortimana tehnicke robe</h1>

<table class="table table-striped" style="  margin-left: -280px;">
  <thead>
    <tr>
      <th>Ap1</th>
      <th>Ap2</th>
      <th>Ap3</th>
      <th>Ap4</th>
      <th>Ap5</th>
      <th>Ap6</th>
      <th>Ap7</th>
      <th>Ap8</th>
      <th>B1</th>
      <th>B2</th>
      <th>B3</th>
      <th>B4</th>
      <th>B5</th>
      <th>B6</th>
      <th>Lokacija</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @technical_goods_assortments.each do |technical_goods_assortment| %>
      <tr>
        <td><%= ApProduct.find(technical_goods_assortment.ap1_id).name %></td>
        <td><%= ApProduct.find(technical_goods_assortment.ap2_id).name %></td>
        <td><%= ApProduct.find(technical_goods_assortment.ap3_id).name %></td>
        <td><%= ApProduct.find(technical_goods_assortment.ap4_id).name %></td>
        <td><%= ApProduct.find(technical_goods_assortment.ap5_id).name %></td>
        <td><%= ApProduct.find(technical_goods_assortment.ap6_id).name %></td>
        <td><%= ApProduct.find(technical_goods_assortment.ap7_id).name %></td>
        <td><%= ApProduct.find(technical_goods_assortment.ap8_id).name %></td>
        <td><%= ApBrand.find(technical_goods_assortment.b1_id).name %></td>
        <td><%= ApBrand.find(technical_goods_assortment.b2_id).name %></td>
        <td><%= ApBrand.find(technical_goods_assortment.b3_id).name %></td>
        <td><%= ApBrand.find(technical_goods_assortment.b4_id).name %></td>
        <td><%= ApBrand.find(technical_goods_assortment.b5_id).name %></td>
        <td><%= ApBrand.find(technical_goods_assortment.b6_id).name %></td>
        <td><%= Location.find(technical_goods_assortment.location_id).name %></td>
        <td><%= link_to 'Show', technical_goods_assortment %></td>
        <td><%= link_to 'Edit', edit_technical_goods_assortment_path(technical_goods_assortment) %></td>
        <td><%= link_to 'Destroy', technical_goods_assortment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novi asortiman tehnickih roba', new_technical_goods_assortment_path %>
 <br>
<%= link_to 'Back', locations_path(@location, url_options), :data => {:no_turbolink =>true} %>

app/views/technical_goods_assortments/new.html.erb
<h1>Novi asortiman tehnicke robe</h1>

<%= render 'form' %>

<%= link_to 'Back', technical_goods_assortments_path %>

app/views/technical_goods_assortments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ap1:</strong>
  <%= @technical_goods_assortment.ap1_id %>
</p>

<p>
  <strong>Ap2:</strong>
  <%= @technical_goods_assortment.ap2_id %>
</p>

<p>
  <strong>Ap3:</strong>
  <%= @technical_goods_assortment.ap3_id %>
</p>

<p>
  <strong>Ap4:</strong>
  <%= @technical_goods_assortment.ap4_id %>
</p>

<p>
  <strong>Ap5:</strong>
  <%= @technical_goods_assortment.ap5_id %>
</p>

<p>
  <strong>Ap6:</strong>
  <%= @technical_goods_assortment.ap6_id %>
</p>

<p>
  <strong>Ap7:</strong>
  <%= @technical_goods_assortment.ap7_id %>
</p>

<p>
  <strong>Ap8:</strong>
  <%= @technical_goods_assortment.ap8_id %>
</p>

<p>
  <strong>B1:</strong>
  <%= @technical_goods_assortment.b1_id %>
</p>

<p>
  <strong>B2:</strong>
  <%= @technical_goods_assortment.b2_id %>
</p>

<p>
  <strong>B3:</strong>
  <%= @technical_goods_assortment.b3_id %>
</p>

<p>
  <strong>B4:</strong>
  <%= @technical_goods_assortment.b4_id %>
</p>

<p>
  <strong>B5:</strong>
  <%= @technical_goods_assortment.b5_id %>
</p>

<p>
  <strong>B6:</strong>
  <%= @technical_goods_assortment.b6_id %>
</p>

<p>
  <strong>Location id:</strong>
  <%= @technical_goods_assortment.location_id %>
</p>
<%= link_to 'Edit', edit_technical_goods_assortment_path(@technical_goods_assortment) %> |
<%= link_to 'Back', technical_goods_assortments_path %>