config/routes.rb
Rails.application.routes.draw do
  get "locations/index"
  get "locations/export"
  get "locations/lokacije"
  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'locations#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  resources :assets

  resources :technical_goods_assortments

  resources :brands

  resources :products

  resources :primary_assortments

  resources :locations_assortments

  resources :sales_specialists

  resources :places

  resources :regions

  resources :locations
   resources :locations do 
    collection do 
      get 'locations/export', :to => 'locations#export'
    end
  end
  get "companies/index"
  get "companies/show"
  get "companies/new"
  get "companies/edit"
   root 'locations#index'
    authenticate :user do
    resources :locations, only: [:new, :create, :edit, :update, :destroy]
    resources :regions, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/ap_brand.rb
class ApBrand < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/ap_product.rb
class ApProduct < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :location , :class_name => "Location"
  attr_accessible :avatar_file_name
  attr_accessible :position, :class_type, :alt, :attachment_width , :attachment_height ,:avatar , :class_type , :typeable_id
  alias_attribute :location_id, :typeable_id
  has_attached_file :avatar, styles: { mini: '48x48#',
                                      small: '150x120>',
                                      home: '185x185#',
                                      product: '240x240>',
  	large: '570x380>' },
    :url  => "/assets/locations/:typeable_id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/locations/:typeable_id/:style/:basename.:extension"
     Paperclip.interpolates :typeable_id do |attachment, style|
    "#{attachment.instance.typeable_id}"
  end
  Paperclip.options[:content_type_mappings] = { jpeg: 'image/jpeg', jpg: 'image/jpeg' }

	
end

app/models/brand.rb
class ApBrand < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_xlsx
	include ActiveModel::ForbiddenAttributesProtection
	include ActiveModel::MassAssignmentSecurity
=begin	 has_attached_file :avatar, styles: { mini: '48x48#',
                                         small: '150x120>',
                                         home: '185x185#',
                                         product: '240x240>',
  									     large: '570x380>' },
    :url  => "/assets/locations/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/locations/:id/:style/:basename.:extension"
	validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
=end
  attr_accessible :address, :latitude, :longitude, :name ,:region_id , :place_id , :customer_character , :contact, :sales_specialist_id , :tel_fax_email , :object_type , :customer_classification , :class_type 
  attr_accessible :asset_params
  belongs_to :sales_specialist
  belongs_to :region
  belongs_to :place
  has_many :locations_assortments , :dependent => :destroy
  has_many :technical_goods_assortments, :dependent => :destroy
  has_many :assets , :dependent => :destroy ,  :foreign_key => 'typeable_id'
  has_many :products , :through => :technical_goods_assortments
  accepts_nested_attributes_for :assets, allow_destroy: true
  accepts_nested_attributes_for :locations_assortments, allow_destroy: true
  accepts_nested_attributes_for :technical_goods_assortments, allow_destroy: true
  attr_accessible :locations_assortments_attributes
  attr_accessible :technical_goods_assortments_attributes
  validates :address, :name ,:region_id , :place_id , :customer_character , :contact, :sales_specialist_id , :tel_fax_email , :object_type , :customer_classification , presence: true 
  geocoded_by :address
	after_validation :geocode , if: ->(obj){ obj.address.present? and obj.address_changed? }
  
  def gmaps4rails_address
      address
  end
 
end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :locations
	belongs_to :region
	
end

app/models/primary_assortment.rb
class PrimaryAssortment < ActiveRecord::Base
	has_many :locations_assortments
	attr_accessible :name
	validates :name, presence: true
end

app/models/product.rb
class ApProduct < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :locations
	has_many :places
	
end

app/models/sales_specialist.rb
class SalesSpecialist < ActiveRecord::Base
	has_many :locations
	attr_accessible :name, :phone
	validates :name, :phone, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #before_action :authenticate_user!
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :location
  attr_accessor :username
  attr_accessible :email
  attr_accessible :password
  attr_accessible :password_confirmation
  attr_accessible :first_name
  attr_accessible :last_name,
  #attr_accessible :encrypted_password ,:reset_password_token,:reset_password_sent_at , :remember_created_at ,
  #:current_sign_in_at,
  #:last_sign_in_at,
  #:current_sign_in_ip ,
  #:last_sign_in_ip ,
  :created_at ,
  :updated_at 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/ap_brands_helper.rb
module ApBrandsHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/brands_helper.rb
module ApBrandsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper

		def slick_slider_image(asset)
		link_to(image_tag(asset.avatar.url(:home) , size:'165x165'))
	end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/products_helper.rb
module ApProductsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/home/index.html.erb
<!--<div class="col-md-12">
<div class="col-md-6">
<%#= link_to "Dodaj novu lokaciju" , new_location_path %> <br>
<%#= link_to "Dodaj novi brand" , new_brand_path %><br>
<%#= link_to "Dodaj novu tehnicku robu" , new_product_path %><br>
<%#= link_to "Dodaj novi primarni asortiman za lokaciju" , new_locations_assortment_path %><br>
<%#= link_to "Dodaj novo sjediste" , new_place_path %><br>
<%#= link_to "Dodaj novi primarni asortiman" , new_primary_assortment_path %><br>
<%#= link_to "Dodaj novu regiju" , new_region_path %><br>
<%#= link_to "Dodaj novi asortiman u okviru tehnicke robe" , new_technical_goods_assortment_path %><br>
<%#= link_to "Dodaj novog komercijalistu" , new_sales_specialist_path %><br>
</div>
<div class="col-md-6">

</div>
</div>
-->
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="tooltip"  data-placement="right" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">Dobrodosli na admin panel</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><%= link_to "Dodaj novu lokaciju" , new_location_path , :class => 'linkic'%></li>
      <li><%= link_to "Dodaj novi brand" , new_brand_path , :class => 'linkic'%></li>
			<li><%= link_to "Dodaj novu tehnicku robu" , new_product_path , :class => 'linkic' %></li>
			<li><%= link_to "Dodaj novi primarni asortiman za lokaciju" , new_locations_assortment_path , :class => 'linkic'%></li>
			<li><%= link_to "Dodaj novo sjediste" , new_place_path, :class => 'linkic' %></li>
			<li><%= link_to "Dodaj novi primarni asortiman" , new_primary_assortment_path, :class => 'linkic' %></li>
			<li><%= link_to "Dodaj novu regiju" , new_region_path , :class => 'linkic'%></li>
			<li><%= link_to "Dodaj novi asortiman u okviru tehnicke robe" , new_technical_goods_assortment_path, :class => 'linkic' %></li>
			<li><%= link_to "Dodaj novog komercijalistu" , new_sales_specialist_path , :class => 'linkic'%></li>
				            </ul>
				            <%= link_to "Idi na mapu",locations_path , :class => 'linkic' %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>