config/routes.rb
Rails.application.routes.draw do
  get "locations/index"
  get "locations/export"
  get "locations/lokacije"
  devise_for :users
  devise_scope :user do
  authenticated :user do
    root 'locations#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end
  resources :assets

  resources :technical_goods_assortments

  resources :brands

  resources :products

  resources :primary_assortments

  resources :locations_assortments

  resources :sales_specialists

  resources :places

  resources :regions

  resources :locations
   resources :locations do 
    collection do 
      get 'locations/export', :to => 'locations#export'
    end
  end
  get "companies/index"
  get "companies/show"
  get "companies/new"
  get "companies/edit"
   root 'locations#index'
    authenticate :user do
    resources :locations, only: [:new, :create, :edit, :update, :destroy]
    resources :regions, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/ap_brand.rb
class ApBrand < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/ap_product.rb
class ApProduct < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :location , :class_name => "Location"
  attr_accessible :avatar_file_name
  attr_accessible :position, :class_type, :alt, :attachment_width , :attachment_height ,:avatar , :class_type , :typeable_id
  alias_attribute :location_id, :typeable_id
  has_attached_file :avatar, styles: { mini: '48x48#',
                                      small: '150x120>',
                                      home: '185x185#',
                                      product: '240x240>',
  	large: '570x380>' },
    :url  => "/assets/locations/:typeable_id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/locations/:typeable_id/:style/:basename.:extension"
     Paperclip.interpolates :typeable_id do |attachment, style|
    "#{attachment.instance.typeable_id}"
  end
  Paperclip.options[:content_type_mappings] = { jpeg: 'image/jpeg', jpg: 'image/jpeg' }

	
end

app/models/brand.rb
class ApBrand < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_xlsx
	include ActiveModel::ForbiddenAttributesProtection
	include ActiveModel::MassAssignmentSecurity
=begin	 has_attached_file :avatar, styles: { mini: '48x48#',
                                         small: '150x120>',
                                         home: '185x185#',
                                         product: '240x240>',
  									     large: '570x380>' },
    :url  => "/assets/locations/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/locations/:id/:style/:basename.:extension"
	validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
=end
  attr_accessible :address, :latitude, :longitude, :name ,:region_id , :place_id , :customer_character , :contact, :sales_specialist_id , :tel_fax_email , :object_type , :customer_classification , :class_type 
  attr_accessible :asset_params
  belongs_to :sales_specialist
  belongs_to :region
  belongs_to :place
  has_many :locations_assortments , :dependent => :destroy
  has_many :technical_goods_assortments, :dependent => :destroy
  has_many :assets , :dependent => :destroy ,  :foreign_key => 'typeable_id'
  has_many :products , :through => :technical_goods_assortments
  accepts_nested_attributes_for :assets, allow_destroy: true
  accepts_nested_attributes_for :locations_assortments, allow_destroy: true
  accepts_nested_attributes_for :technical_goods_assortments, allow_destroy: true
  attr_accessible :locations_assortments_attributes
  attr_accessible :technical_goods_assortments_attributes
  validates :address, :name ,:region_id , :place_id , :customer_character , :contact, :sales_specialist_id , :tel_fax_email , :object_type , :customer_classification , presence: true 
  geocoded_by :address
	after_validation :geocode , if: ->(obj){ obj.address.present? and obj.address_changed? }
  
  def gmaps4rails_address
      address
  end
 
end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :locations
	belongs_to :region
	
end

app/models/primary_assortment.rb
class PrimaryAssortment < ActiveRecord::Base
	has_many :locations_assortments
	attr_accessible :name
	validates :name, presence: true
end

app/models/product.rb
class ApProduct < ActiveRecord::Base
	belongs_to :technical_goods_assortment
	
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :locations
	has_many :places
	
end

app/models/sales_specialist.rb
class SalesSpecialist < ActiveRecord::Base
	has_many :locations
	attr_accessible :name, :phone
	validates :name, :phone, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #before_action :authenticate_user!
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :location
  attr_accessor :username
  attr_accessible :email
  attr_accessible :password
  attr_accessible :password_confirmation
  attr_accessible :first_name
  attr_accessible :last_name,
  #attr_accessible :encrypted_password ,:reset_password_token,:reset_password_sent_at , :remember_created_at ,
  #:current_sign_in_at,
  #:last_sign_in_at,
  #:current_sign_in_ip ,
  #:last_sign_in_ip ,
  :created_at ,
  :updated_at 
end

app/controllers/sales_specialists_controller.rb
class SalesSpecialistsController < ApplicationController
  before_action :set_sales_specialist, only: [:show, :edit, :update, :destroy]

  # GET /sales_specialists
  # GET /sales_specialists.json
  def index
    @sales_specialists = SalesSpecialist.all
  end

  # GET /sales_specialists/1
  # GET /sales_specialists/1.json
  def show
  end

  # GET /sales_specialists/new
  def new
    @sales_specialist = SalesSpecialist.new
  end

  # GET /sales_specialists/1/edit
  def edit
  end

  # POST /sales_specialists
  # POST /sales_specialists.json
  def create
    @sales_specialist = SalesSpecialist.new(sales_specialist_params)

    respond_to do |format|
      if @sales_specialist.save
        format.html { redirect_to @sales_specialist, notice: 'Sales specialist was successfully created.' }
        format.json { render :show, status: :created, location: @sales_specialist }
      else
        format.html { render :new }
        format.json { render json: @sales_specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_specialists/1
  # PATCH/PUT /sales_specialists/1.json
  def update
    respond_to do |format|
      if @sales_specialist.update(sales_specialist_params)
        format.html { redirect_to @sales_specialist, notice: 'Sales specialist was successfully updated.' }
        format.json { render :show, status: :ok, location: @sales_specialist }
      else
        format.html { render :edit }
        format.json { render json: @sales_specialist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_specialists/1
  # DELETE /sales_specialists/1.json
  def destroy
    @sales_specialist.destroy
    respond_to do |format|
      format.html { redirect_to sales_specialists_url, notice: 'Sales specialist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_specialist
      @sales_specialist = SalesSpecialist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sales_specialist_params
      params.require(:sales_specialist).permit(:name, :phone)
    end
end

app/helpers/ap_brands_helper.rb
module ApBrandsHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/brands_helper.rb
module ApBrandsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper

		def slick_slider_image(asset)
		link_to(image_tag(asset.avatar.url(:home) , size:'165x165'))
	end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/products_helper.rb
module ApProductsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sales_specialists_helper.rb
module SalesSpecialistsHelper
end

app/views/sales_specialists/_form.html.erb
<%= form_for(@sales_specialist) do |f| %>
  <% if @sales_specialist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sales_specialist.errors.count, "error") %> prohibited this sales_specialist from being saved:</h2>

      <ul>
      <% @sales_specialist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Ime i prezime" %><br>
    <%= f.text_field :name , :class => "form-control"%>
  </div>
  <div class="field">
    <%= f.label :telefon %><br>
    <%= f.text_field :phone , :class => "form-control"%>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Spasi" %>
  </div>
<% end %>

app/views/sales_specialists/edit.html.erb
<h1>Uredi komercijalistu</h1>

<%= render 'form' %>

<%= link_to 'Show', @sales_specialist %> |
<%= link_to 'Back', sales_specialists_path %>

app/views/sales_specialists/index.html.erb
<h1>Listing komercijalista</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Ime i prezime</th>
      <th>Telefon</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sales_specialists.each do |sales_specialist| %>
      <tr>
        <td><%= sales_specialist.name %></td>
        <td><%= sales_specialist.phone %></td>
        <td><%= link_to 'Show', sales_specialist %></td>
        <td><%= link_to 'Edit', edit_sales_specialist_path(sales_specialist) %></td>
        <td><%= link_to 'Destroy', sales_specialist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novi komercijalista', new_sales_specialist_path %>
<br>
<%= link_to ' Back', locations_path(@location, url_options), :data => {:no_turbolink =>true} %>

app/views/sales_specialists/new.html.erb
<h1>Novi komercijalista</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_specialists_path %>

app/views/sales_specialists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Naziv:</strong>
  <%= @sales_specialist.name %>
</p>

<p>
  <strong>Telefon:</strong>
  <%= @sales_specialist.phone %>
</p>

<%= link_to 'Edit', edit_sales_specialist_path(@sales_specialist) %> |
<%= link_to 'Back', sales_specialists_path %>